# Generated by Django 5.1.6 on 2025-02-10 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis_app', '0003_user_tipo_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ImageCasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='casa_images/')),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='imoveis_app.casa')),
            ],
        ),
    ]
